# Generated by Django 3.1.7 on 2021-03-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210304_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmstring',
            options={'ordering': ['-c_time'], 'verbose_name': '确认码', 'verbose_name_plural': '确认码'},
        ),
        migrations.AlterModelOptions(
            name='userdetail',
            options={'ordering': ['-last_edit'], 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
