# Generated by Django 3.1.7 on 2021-03-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210304_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='username',
            new_name='user',
        ),
    ]
