# Generated by Django 3.1.7 on 2021-03-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210304_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='nickname',
            field=models.CharField(default='喵帕斯', max_length=128, verbose_name='昵称'),
        ),
    ]
