# Generated by Django 3.1.4 on 2021-03-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userdetail_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.CharField(max_length=128, verbose_name='修改用户')),
                ('login_time', models.TimeField(auto_now_add=True, verbose_name='登录时间')),
                ('login_ip', models.CharField(max_length=31, verbose_name='IP')),
            ],
            options={
                'verbose_name': '登录纪录',
                'verbose_name_plural': '登录纪录',
                'ordering': ['-login_time'],
            },
        ),
    ]
