# Generated by Django 3.1.4 on 2021-03-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_loginrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登录时间'),
        ),
    ]
