# Generated by Django 3.1.7 on 2021-03-26 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210323_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginrecord',
            name='login_user',
            field=models.CharField(max_length=128, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='ForgetString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-c_time'],
            },
        ),
    ]
