# Generated by Django 3.1.7 on 2021-03-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20210326_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forgetstring',
            options={'ordering': ['-c_time'], 'verbose_name': '重置码', 'verbose_name_plural': '重置码'},
        ),
        migrations.AlterField(
            model_name='forgetstring',
            name='user',
            field=models.CharField(max_length=128),
        ),
    ]
