# Generated by Django 3.1.7 on 2021-03-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20210326_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgetstring',
            old_name='user',
            new_name='username',
        ),
    ]
