# Generated by Django 3.1.7 on 2021-03-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20210326_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='birthdate',
            field=models.DateField(auto_now=True),
        ),
    ]
