# Generated by Django 3.1.7 on 2021-03-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_userdetail_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='birthdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
