# Generated by Django 3.1.7 on 2021-03-31 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20210331_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='birthdate',
            new_name='birthday',
        ),
    ]
