# Generated by Django 3.1.4 on 2021-03-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnSetence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setence', models.CharField(max_length=512, verbose_name='句子')),
                ('translation', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': '句子',
                'verbose_name_plural': '句子',
                'ordering': ['setence'],
            },
        ),
        migrations.CreateModel(
            name='EnWords',
            fields=[
                ('word', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='单词')),
                ('translation', models.CharField(max_length=512, verbose_name='翻译')),
                ('cet4', models.BooleanField(verbose_name='四级')),
                ('cet6', models.BooleanField(verbose_name='六级')),
                ('highschool', models.BooleanField(verbose_name='高中')),
                ('other_type', models.CharField(max_length=128, verbose_name='其它类型')),
            ],
            options={
                'verbose_name': '单词',
                'verbose_name_plural': '单词',
                'ordering': ['word'],
            },
        ),
    ]
