# Generated by Django 3.1.7 on 2021-04-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(default=1000, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('finish', models.BooleanField(verbose_name='if_finish')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField()),
                ('first_letter', models.CharField(default='0', max_length=1)),
                ('type', models.CharField(default='R', max_length=1, verbose_name='CheckType')),
            ],
        ),
        migrations.CreateModel(
            name='CheckWordL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.IntegerField(verbose_name='CheckID')),
                ('word', models.CharField(max_length=20, verbose_name='ENGWORD')),
                ('error_or_correct', models.BooleanField()),
                ('if_do', models.BooleanField()),
            ],
            options={
                'verbose_name': '单词',
                'verbose_name_plural': '单词',
                'ordering': ['-check_id'],
            },
        ),
        migrations.CreateModel(
            name='CheckwordR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.IntegerField(verbose_name='CheckID')),
                ('word', models.CharField(max_length=20, verbose_name='ENGWORD')),
                ('error_or_correct', models.BooleanField()),
                ('if_do', models.BooleanField()),
            ],
            options={
                'verbose_name': '单词',
                'verbose_name_plural': '单词',
                'ordering': ['-check_id'],
            },
        ),
    ]
