# Generated by Django 3.1.7 on 2021-04-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='check_num',
            field=models.IntegerField(default=10),
        ),
    ]
