# Generated by Django 3.1.7 on 2021-04-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_check_check_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='first_letter',
        ),
        migrations.AddField(
            model_name='checkwordl',
            name='letter',
            field=models.CharField(default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='checkwordl',
            name='username',
            field=models.CharField(default='null', max_length=64, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='checkwordr',
            name='username',
            field=models.CharField(default='null', max_length=64, verbose_name='用户名'),
        ),
    ]
