# Generated by Django 3.1.7 on 2021-04-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_auto_20210403_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='last_edit',
        ),
    ]
