# Generated by Django 3.1.7 on 2021-04-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_remove_check_last_edit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'ordering': ['-id'], 'verbose_name': '检查纪录', 'verbose_name_plural': '检查纪录'},
        ),
        migrations.AlterModelOptions(
            name='checkwordl',
            options={'ordering': ['-check_id'], 'verbose_name': '首字母单词', 'verbose_name_plural': '首字母单词'},
        ),
        migrations.AlterModelOptions(
            name='checkwordr',
            options={'ordering': ['-check_id'], 'verbose_name': '随机单词', 'verbose_name_plural': '随机单词'},
        ),
        migrations.AlterField(
            model_name='checkwordl',
            name='error_or_correct',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='checkwordr',
            name='error_or_correct',
            field=models.BooleanField(null=True),
        ),
    ]
