# Generated by Django 3.1.7 on 2021-04-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_auto_20210404_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.IntegerField(verbose_name='CheckID')),
                ('error_num', models.IntegerField(verbose_name='错误数')),
                ('score', models.FloatField(verbose_name='Score')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '结果',
                'verbose_name_plural': '结果',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='checkwordl',
            name='ResultWord',
            field=models.CharField(default='', max_length=20, verbose_name='ResultWord'),
        ),
        migrations.AddField(
            model_name='checkwordr',
            name='ResultWord',
            field=models.CharField(default='', max_length=20, verbose_name='ResultWord'),
        ),
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(default='r', max_length=1, verbose_name='CheckType'),
        ),
    ]
