# Generated by Django 3.1.7 on 2021-04-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_auto_20210405_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkwordl',
            old_name='ResultWord',
            new_name='result_word',
        ),
        migrations.RenameField(
            model_name='checkwordr',
            old_name='ResultWord',
            new_name='result_word',
        ),
        migrations.AlterField(
            model_name='check',
            name='finish_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
